site_name: ScholarSphere Documentation (DRAFT)
theme:
  name: readthedocs
  custom_dir: theme_overrides/
nav:
  - 'Guides':
    - 'Deposit Overview': 'guides/deposit-overview.md'
    - 'Depositing Journal Article Postprints': 'guides/journal-article.md'
    - 'Depositing Data & Code': 'guides/dataset.md'
    - 'Choosing a License':  'guides/licenses.md'
    - 'Writing a README':  'guides/writing-readme.md'
    - 'Collections of Student Work': 'guides/collections.md'
  - 'FAQ': faq.md
